/**
 * @file ui_maingallerywindow.h
 * @brief This file is automatically generated by the Qt User Interface Compiler (uic)
 * from reading the UI file 'maingallerywindow.ui'.
 *
 * @warning ALL MANUAL CHANGES TO THIS FILE WILL BE LOST WHEN THE UI FILE IS RECOMPILED!
 * It is crucial not to modify this file directly.
 *
 * It contains the UI class definition for the main gallery window,
 * including user interface elements (widgets) and methods for their
 * setup and translation.
 */

#ifndef UI_MAINGALLERYWINDOW_H
#define UI_MAINGALLERYWINDOW_H

#include <QtCore/QVariant>
#include <QtWidgets/QApplication>
#include <QtWidgets/QFrame>
#include <QtWidgets/QHBoxLayout>
#include <QtWidgets/QLabel>
#include <QtWidgets/QMainWindow>
#include <QtWidgets/QPushButton>
#include <QtWidgets/QSpacerItem>
#include <QtWidgets/QVBoxLayout>
#include <QtWidgets/QWidget>

QT_BEGIN_NAMESPACE


/**
 * @brief The Ui_MainGalleryWindow class defines the structure of the user interface
 * for the MainGalleryWindow.
 *
 * This class is generated by Qt Designer and contains the declaration of all widgets
 * present in the .ui file, as well as methods to configure them (`setupUi`) and translate texts
 * (`retranslateUi`). It should not be manually modified.
 */
class Ui_MainGalleryWindow
{
public:
    QWidget *centralwidget;          /**< @brief The central widget of the main window. */
    QVBoxLayout *verticalLayout;     /**< @brief The main vertical layout for the central widget. */
    QFrame *imageFrame;              /**< @brief A frame to contain the image display. */
    QVBoxLayout *verticalLayout_2;   /**< @brief Vertical layout within the image frame. */
    QLabel *imageLabel;              /**< @brief Label to display the image. */
    QHBoxLayout *horizontalLayout;   /**< @brief Horizontal layout for navigation buttons and ID label. */
    QSpacerItem *horizontalSpacer_2; /**< @brief Spacer on the left of the navigation buttons. */
    QPushButton *prevButton;         /**< @brief Button to navigate to the previous image. */
    QLabel *idLabel;                 /**< @brief Label to display the current image ID and total count. */
    QPushButton *nextButton;         /**< @brief Button to navigate to the next image. */
    QSpacerItem *horizontalSpacer;   /**< @brief Spacer on the right of the navigation buttons. */

    /**
     * @brief Sets up the user interface for the MainGalleryWindow.
     *
     * This method initializes and arranges all UI elements (widgets)
     * within the provided QMainWindow. It sets object names, sizes,
     * layouts, and connects signals/slots.
     *
     * @param MainGalleryWindow Pointer to the QMainWindow for which the UI is to be set up.
     */
    void setupUi(QMainWindow *MainGalleryWindow)
    {
        if (MainGalleryWindow->objectName().isEmpty())
            MainGalleryWindow->setObjectName("MainGalleryWindow");
        MainGalleryWindow->resize(1024, 768);
        centralwidget = new QWidget(MainGalleryWindow);
        centralwidget->setObjectName("centralwidget");
        verticalLayout = new QVBoxLayout(centralwidget);
        verticalLayout->setObjectName("verticalLayout");
        imageFrame = new QFrame(centralwidget);
        imageFrame->setObjectName("imageFrame");
        imageFrame->setMinimumSize(QSize(640, 480));
        imageFrame->setStyleSheet(QString::fromUtf8("\n"
"        /* Rounded corners for the image frame */\n"
"        QFrame#imageFrame {\n"
"            border: 2px solid lightgray;\n"
"            border-radius: 20px; /* Adjust as needed for desired roundness */\n"
"            background-color: black; /* Placeholder background */\n"
"        }\n"
"       "));
        imageFrame->setFrameShape(QFrame::StyledPanel);
        imageFrame->setFrameShadow(QFrame::Raised);
        verticalLayout_2 = new QVBoxLayout(imageFrame);
        verticalLayout_2->setObjectName("verticalLayout_2");
        imageLabel = new QLabel(imageFrame);
        imageLabel->setObjectName("imageLabel");
        imageLabel->setAlignment(Qt::AlignCenter);

        verticalLayout_2->addWidget(imageLabel);


        verticalLayout->addWidget(imageFrame);

        horizontalLayout = new QHBoxLayout();
        horizontalLayout->setSpacing(20);
        horizontalLayout->setObjectName("horizontalLayout");
        horizontalLayout->setContentsMargins(0, 10, 0, 0);
        horizontalSpacer_2 = new QSpacerItem(40, 20, QSizePolicy::Policy::Expanding, QSizePolicy::Policy::Minimum);

        horizontalLayout->addItem(horizontalSpacer_2);

        prevButton = new QPushButton(centralwidget);
        prevButton->setObjectName("prevButton");
        prevButton->setMinimumSize(QSize(60, 60));
        prevButton->setMaximumSize(QSize(60, 60));
        prevButton->setIconSize(QSize(40, 40));

        horizontalLayout->addWidget(prevButton);

        idLabel = new QLabel(centralwidget);
        idLabel->setObjectName("idLabel");
        idLabel->setAlignment(Qt::AlignCenter);

        horizontalLayout->addWidget(idLabel);

        nextButton = new QPushButton(centralwidget);
        nextButton->setObjectName("nextButton");
        nextButton->setMinimumSize(QSize(60, 60));
        nextButton->setMaximumSize(QSize(60, 60));
        nextButton->setIconSize(QSize(40, 40));

        horizontalLayout->addWidget(nextButton);

        horizontalSpacer = new QSpacerItem(40, 20, QSizePolicy::Policy::Expanding, QSizePolicy::Policy::Minimum);

        horizontalLayout->addItem(horizontalSpacer);


        verticalLayout->addLayout(horizontalLayout);

        MainGalleryWindow->setCentralWidget(centralwidget);

        retranslateUi(MainGalleryWindow);

        QMetaObject::connectSlotsByName(MainGalleryWindow);
    } // setupUi

    /**
     * @brief Retranslates the user interface texts.
     *
     * This method sets the visible texts on the UI widgets.
     * It is typically called after `setupUi` and can be re-called to
     * support application language changes.
     *
     * @param MainGalleryWindow Pointer to the QMainWindow whose texts are to be retranslated.
     */
    void retranslateUi(QMainWindow *MainGalleryWindow)
    {
        MainGalleryWindow->setWindowTitle(QCoreApplication::translate("MainGalleryWindow", "Qt Image Gallery", nullptr));
        imageLabel->setText(QCoreApplication::translate("MainGalleryWindow", "Loading Image...", nullptr));
        prevButton->setText(QString());
        idLabel->setText(QCoreApplication::translate("MainGalleryWindow", "ID: 0/0", nullptr));
        nextButton->setText(QString());
    } // retranslateUi

};

namespace Ui {
    /**
     * @brief Alias for the Ui_MainGalleryWindow class within the Ui namespace.
     *
     * This alias simplifies the usage of the class generated by the UI Designer,
     * allowing it to be referred to as `Ui::MainGalleryWindow`.
     */
    class MainGalleryWindow: public Ui_MainGalleryWindow {};
} // namespace Ui

QT_END_NAMESPACE

#endif // UI_MAINGALLERYWINDOW_H
